export const casteOptions = [
  {
    value: "Caste no bar",
    label: "Caste no bar",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Mudaliyar",
    label: "Mudaliyar",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "24 Manai Telugu Chettiar",
    label: "24 Manai Telugu Chettiar",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "96 Kuli Maratha",
    label: "96 Kuli Maratha",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Aaru Nattu Vellala",
    label: "Aaru Nattu Vellala",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Achirapakkam Chettiar",
    label: "Achirapakkam Chettiar",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Ad Dharmi",
    label: "Ad Dharmi",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Adi Andhra",
    label: "Adi Andhra",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Adi Dravidar",
    label: "Adi Dravidar",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Adi Karnataka",
    label: "Adi Karnataka",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Agamudayar / Arcot / Thuluva Vellala",
    label: "Agamudayar / Arcot / Thuluva Vellala",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Agaram Vellan Chettiar",
    label: "Agaram Vellan Chettiar",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Agarwal", label: "Agarwal", relig: "Hindu", religAll: "interCast" },
  {
    value: "Agnikula Kshatriya",
    label: "Agnikula Kshatriya",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Agrahari",
    label: "Agrahari",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Agri", label: "Agri", relig: "Hindu", religAll: "interCast" },
  {
    value: "Aguri / Ugra Kshatriya",
    label: "Aguri / Ugra Kshatriya",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Aheriya", label: "Aheriya", relig: "Hindu", religAll: "interCast" },
  {
    value: "Ahir Shimpi",
    label: "Ahir Shimpi",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Ahirwar", label: "Ahirwar", relig: "Hindu", religAll: "interCast" },
  { value: "Ahom", label: "Ahom", relig: "Hindu", religAll: "interCast" },
  {
    value: "Ambalavasi",
    label: "Ambalavasi",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Amma Kodava",
    label: "Amma Kodava",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Anjana (Chowdary) Pate",
    label: "Anjana (Chowdary) Pate",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Arakh / Arakvanshiya",
    label: "Arakh / Arakvanshiya",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Aramari / Gabit",
    label: "Aramari / Gabit",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Arekatica",
    label: "Arekatica",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Arora", label: "Arora", relig: "Hindu", religAll: "interCast" },
  {
    value: "Arunthathiyar",
    label: "Arunthathiyar",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Arya Vysya",
    label: "Arya Vysya",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Asathi", label: "Asathi", relig: "Hindu", religAll: "interCast" },
  {
    value: "Ayira Vysya",
    label: "Ayira Vysya",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Ayodhyavasi",
    label: "Ayodhyavasi",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Ayyaraka",
    label: "Ayyaraka",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Badaga", label: "Badaga", relig: "Hindu", religAll: "interCast" },
  { value: "Bagdi", label: "Bagdi", relig: "Hindu", religAll: "interCast" },
  { value: "Baidya", label: "Baidya", relig: "Hindu", religAll: "interCast" },
  { value: "Bairagi", label: "Bairagi", relig: "Hindu", religAll: "interCast" },
  { value: "Bairwa", label: "Bairwa", relig: "Hindu", religAll: "interCast" },
  {
    value: "Baishnab",
    label: "Baishnab",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Baishya", label: "Baishya", relig: "Hindu", religAll: "interCast" },
  {
    value: "Bajantri",
    label: "Bajantri",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Balai", label: "Balai", relig: "Hindu", religAll: "interCast" },
  { value: "Balija", label: "Balija", relig: "Hindu", religAll: "interCast" },
  {
    value: "Balija Naidu",
    label: "Balija Naidu",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Balija Reddy",
    label: "Balija Reddy",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Banayat Oriya",
    label: "Banayat Oriya",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Banik", label: "Banik", relig: "Hindu", religAll: "interCast" },
  { value: "Baniya", label: "Baniya", relig: "Hindu", religAll: "interCast" },
  {
    value: "Baniya - Bania",
    label: "Baniya - Bania",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Baniya - Kumuti",
    label: "Baniya - Kumuti",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Banjara", label: "Banjara", relig: "Hindu", religAll: "interCast" },
  { value: "Baori", label: "Baori", relig: "Hindu", religAll: "interCast" },
  { value: "Barai", label: "Barai", relig: "Hindu", religAll: "interCast" },
  { value: "Bargi", label: "Bargi", relig: "Hindu", religAll: "interCast" },
  { value: "Bari", label: "Bari", relig: "Hindu", religAll: "interCast" },
  { value: "Baria", label: "Baria", relig: "Hindu", religAll: "interCast" },
  { value: "Barnwal", label: "Barnwal", relig: "Hindu", religAll: "interCast" },
  {
    value: "Barujibi",
    label: "Barujibi",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Bavaria", label: "Bavaria", relig: "Hindu", religAll: "interCast" },
  { value: "Bazigar", label: "Bazigar", relig: "Hindu", religAll: "interCast" },
  { value: "Beldar", label: "Beldar", relig: "Hindu", religAll: "interCast" },
  {
    value: "Beri Chettiar",
    label: "Beri Chettiar",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Besta", label: "Besta", relig: "Hindu", religAll: "interCast" },
  { value: "Bhand", label: "Bhand", relig: "Hindu", religAll: "interCast" },
  {
    value: "Bhandari",
    label: "Bhandari",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Bhar", label: "Bhar", relig: "Hindu", religAll: "interCast" },
  {
    value: "Bharbhunja",
    label: "Bharbhunja",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Bhatia", label: "Bhatia", relig: "Hindu", religAll: "interCast" },
  {
    value: "Bhatraju",
    label: "Bhatraju",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Bhavasar Kshatriya",
    label: "Bhavasar Kshatriya",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Bhil", label: "Bhil", relig: "Hindu", religAll: "interCast" },
  { value: "Bhoi", label: "Bhoi", relig: "Hindu", religAll: "interCast" },
  { value: "Bhovi", label: "Bhovi", relig: "Hindu", religAll: "interCast" },
  { value: "Bhoyar", label: "Bhoyar", relig: "Hindu", religAll: "interCast" },
  {
    value: "Bhulia / Meher",
    label: "Bhulia / Meher",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Billava", label: "Billava", relig: "Hindu", religAll: "interCast" },
  { value: "Bind", label: "Bind", relig: "Hindu", religAll: "interCast" },
  {
    value: "Bishnoi/Vishnoi",
    label: "Bishnoi/Vishnoi",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Bondili", label: "Bondili", relig: "Hindu", religAll: "interCast" },
  { value: "Boyar", label: "Boyar", relig: "Hindu", religAll: "interCast" },
  {
    value: "Brahmakshtriya",
    label: "Brahmakshtriya",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Brahmbatt",
    label: "Brahmbatt",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Brahmin - All",
    label: "Brahmin - All",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Brahmin - Anavil",
    label: "Brahmin - Anavil",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Brahmin - Anaviln Desai",
    label: "Brahmin - Anaviln Desai",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Brahmin - Audichya",
    label: "Brahmin - Audichya",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Brahmin - Bagra",
    label: "Brahmin - Bagra",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Brahmin - Baidhiki/Vaidhiki",
    label: "Brahmin - Baidhiki/Vaidhiki",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Brahmin - Baragaon",
    label: "Brahmin - Baragaon",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Brahmin - Bardai",
    label: "Brahmin - Bardai",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Brahmin - Barendra",
    label: "Brahmin - Barendra",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Brahmin - Bhargav",
    label: "Brahmin - Bhargav",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Brahmin - Bhatt",
    label: "Brahmin - Bhatt",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Brahmin - Bhojak",
    label: "Brahmin - Bhojak",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Brahmin - Bhumihar",
    label: "Brahmin - Bhumihar",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Brahmin - Chaubisa",
    label: "Brahmin - Chaubisa",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Brahmin - Dadhich",
    label: "Brahmin - Dadhich",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Brahmin - Daivadnya",
    label: "Brahmin - Daivadnya",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Brahmin - Dakaut",
    label: "Brahmin - Dakaut",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Brahmin - Danua",
    label: "Brahmin - Danua",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Brahmin - Deshastha",
    label: "Brahmin - Deshastha",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Brahmin - Dhiman",
    label: "Brahmin - Dhiman",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Brahmin - Dravida",
    label: "Brahmin - Dravida",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Brahmin - Embrandiri",
    label: "Brahmin - Embrandiri",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Brahmin - Garhwali",
    label: "Brahmin - Garhwali",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Brahmin - Gaur",
    label: "Brahmin - Gaur",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Brahmin - Goswami/Gosavi",
    label: "Brahmin - Goswami/Gosavi",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Brahmin - Gujar Gaur",
    label: "Brahmin - Gujar Gaur",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Brahmin - Gurukkal",
    label: "Brahmin - Gurukkal",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Brahmin - Halua",
    label: "Brahmin - Halua",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Brahmin - Havyaka",
    label: "Brahmin - Havyaka",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Brahmin - Hoysala",
    label: "Brahmin - Hoysala",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Brahmin - Iyengar",
    label: "Brahmin - Iyengar",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Brahmin - Iyer",
    label: "Brahmin - Iyer",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Brahmin - Jangid",
    label: "Brahmin - Jangid",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Brahmin - Jhadua",
    label: "Brahmin - Jhadua",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Brahmin - Jyotish",
    label: "Brahmin - Jyotish",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Brahmin - Kanyakubj",
    label: "Brahmin - Kanyakubj",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Brahmin - Karhade",
    label: "Brahmin - Karhade",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Brahmin - Khadayata",
    label: "Brahmin - Khadayata",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Brahmin - Khandelwal",
    label: "Brahmin - Khandelwal",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Brahmin - Khedaval",
    label: "Brahmin - Khedaval",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Brahmin - Kokanastha",
    label: "Brahmin - Kokanastha",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Brahmin - Kota",
    label: "Brahmin - Kota",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Brahmin - Koteshwara / Kota (Madhwa )",
    label: "Brahmin - Koteshwara / Kota (Madhwa )",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Brahmin - Kulin",
    label: "Brahmin - Kulin",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Brahmin - Kumaoni",
    label: "Brahmin - Kumaoni",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Brahmin - Madhwa",
    label: "Brahmin - Madhwa",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Brahmin - Maithil",
    label: "Brahmin - Maithil",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Brahmin - Mevada",
    label: "Brahmin - Mevada",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Brahmin - Modh",
    label: "Brahmin - Modh",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Brahmin - Mohyal",
    label: "Brahmin - Mohyal",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Brahmin - Nagar",
    label: "Brahmin - Nagar",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Brahmin - Namboodiri",
    label: "Brahmin - Namboodiri",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Brahmin - Narmadiya",
    label: "Brahmin - Narmadiya",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Brahmin - Niyogi",
    label: "Brahmin - Niyogi",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Brahmin - Others",
    label: "Brahmin - Others",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Brahmin - Paliwal",
    label: "Brahmin - Paliwal",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Brahmin - Panda",
    label: "Brahmin - Panda",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Brahmin - Pandit",
    label: "Brahmin - Pandit",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Brahmin - Panicker",
    label: "Brahmin - Panicker",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Brahmin - Pareek",
    label: "Brahmin - Pareek",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Brahmin - Pushkarna",
    label: "Brahmin - Pushkarna",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Brahmin - Rajgor",
    label: "Brahmin - Rajgor",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Brahmin - Rarhi",
    label: "Brahmin - Rarhi",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Brahmin - Rarhi/Radhi",
    label: "Brahmin - Rarhi/Radhi",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Brahmin - Rigvedi",
    label: "Brahmin - Rigvedi",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Brahmin - Rudraj",
    label: "Brahmin - Rudraj",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Brahmin - Sakaldwipi",
    label: "Brahmin - Sakaldwipi",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Brahmin - Sanadya",
    label: "Brahmin - Sanadya",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Brahmin - Sanketi",
    label: "Brahmin - Sanketi",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Brahmin - Saraswat",
    label: "Brahmin - Saraswat",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Brahmin - Sarua",
    label: "Brahmin - Sarua",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Brahmin - Saryuparin",
    label: "Brahmin - Saryuparin",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Brahmin - Shivalli (Madhva)",
    label: "Brahmin - Shivalli (Madhva)",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Brahmin - Shivhalli",
    label: "Brahmin - Shivhalli",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Brahmin - Shri Gaud",
    label: "Brahmin - Shri Gaud",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Brahmin - Shri Mali",
    label: "Brahmin - Shri Mali",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Brahmin - Shrimali",
    label: "Brahmin - Shrimali",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Brahmin - Shukla Yajurvedi",
    label: "Brahmin - Shukla Yajurvedi",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Brahmin - Sikhwal",
    label: "Brahmin - Sikhwal",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Brahmin - Smartha",
    label: "Brahmin - Smartha",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Brahmin - Sri Vaishnava",
    label: "Brahmin - Sri Vaishnava",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Brahmin - Stanika",
    label: "Brahmin - Stanika",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Brahmin - Tapodhan",
    label: "Brahmin - Tapodhan",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Brahmin - Tyagi",
    label: "Brahmin - Tyagi",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Brahmin - Vaidiki",
    label: "Brahmin - Vaidiki",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Brahmin - Vaikhanasa",
    label: "Brahmin - Vaikhanasa",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Brahmin - Valam",
    label: "Brahmin - Valam",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Brahmin - Velanadu",
    label: "Brahmin - Velanadu",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Brahmin - Vyas",
    label: "Brahmin - Vyas",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Brahmin - Zalora",
    label: "Brahmin - Zalora",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Brajastha Maithil",
    label: "Brajastha Maithil",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Bunt (Shetty)",
    label: "Bunt (Shetty)",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "CKP", label: "CKP", relig: "Hindu", religAll: "interCast" },
  {
    value: "Chakkala Nair",
    label: "Chakkala Nair",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Chalawadi and Holeya",
    label: "Chalawadi and Holeya",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Chambhar",
    label: "Chambhar",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Chandravanshi Kahar",
    label: "Chandravanshi Kahar",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Charan", label: "Charan", relig: "Hindu", religAll: "interCast" },
  { value: "Chasa", label: "Chasa", relig: "Hindu", religAll: "interCast" },
  {
    value: "Chattada Sri Vaishnava",
    label: "Chattada Sri Vaishnava",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Chaturth",
    label: "Chaturth",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Chaudary",
    label: "Chaudary",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Chaurasia",
    label: "Chaurasia",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Chennadasar",
    label: "Chennadasar",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Cherakula Vellalar",
    label: "Cherakula Vellalar",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Chero", label: "Chero", relig: "Hindu", religAll: "interCast" },
  {
    value: "Chettiar",
    label: "Chettiar",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Chhetri", label: "Chhetri", relig: "Hindu", religAll: "interCast" },
  {
    value: "Chippolu (Mera)",
    label: "Chippolu (Mera)",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Choudhary",
    label: "Choudhary",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Coorgi", label: "Coorgi", relig: "Hindu", religAll: "interCast" },
  {
    value: "Dasapalanjika / Kannada Saineegar",
    label: "Dasapalanjika / Kannada Saineegar",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Deshmukh",
    label: "Deshmukh",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Desikar", label: "Desikar", relig: "Hindu", religAll: "interCast" },
  {
    value: "Desikar Thanjavur",
    label: "Desikar Thanjavur",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Devadiga",
    label: "Devadiga",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Devandra Kula Vellalar",
    label: "Devandra Kula Vellalar",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Devang Koshthi",
    label: "Devang Koshthi",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Devanga", label: "Devanga", relig: "Hindu", religAll: "interCast" },
  {
    value: "Devanga Chettiar",
    label: "Devanga Chettiar",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Devar/Thevar/Mukkulathor",
    label: "Devar/Thevar/Mukkulathor",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Devrukhe Brahmin",
    label: "Devrukhe Brahmin",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Dhakad", label: "Dhakad", relig: "Hindu", religAll: "interCast" },
  { value: "Dhanak", label: "Dhanak", relig: "Hindu", religAll: "interCast" },
  { value: "Dhangar", label: "Dhangar", relig: "Hindu", religAll: "interCast" },
  { value: "Dhanka", label: "Dhanka", relig: "Hindu", religAll: "interCast" },
  { value: "Dhanuk", label: "Dhanuk", relig: "Hindu", religAll: "interCast" },
  {
    value: "Dheevara",
    label: "Dheevara",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Dhiman", label: "Dhiman", relig: "Hindu", religAll: "interCast" },
  { value: "Dhoba", label: "Dhoba", relig: "Hindu", religAll: "interCast" },
  {
    value: "Dhor / Kakkayya",
    label: "Dhor / Kakkayya",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Dommala", label: "Dommala", relig: "Hindu", religAll: "interCast" },
  {
    value: "Dosar / Dusra",
    label: "Dosar / Dusra",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Dumal", label: "Dumal", relig: "Hindu", religAll: "interCast" },
  {
    value: "Dusadh (Paswan)",
    label: "Dusadh (Paswan)",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Ediga", label: "Ediga", relig: "Hindu", religAll: "interCast" },
  {
    value: "Ediga /Goud (Balija)",
    label: "Ediga /Goud (Balija)",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Elur Chetty",
    label: "Elur Chetty",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Ezhava", label: "Ezhava", relig: "Hindu", religAll: "interCast" },
  {
    value: "Ezhava Panicker",
    label: "Ezhava Panicker",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Ezhava Thandan",
    label: "Ezhava Thandan",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Ezhuthachan",
    label: "Ezhuthachan",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Gabit", label: "Gabit", relig: "Hindu", religAll: "interCast" },
  { value: "Gahoi", label: "Gahoi", relig: "Hindu", religAll: "interCast" },
  {
    value: "Gajula / Kavarai",
    label: "Gajula / Kavarai",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Ganda", label: "Ganda", relig: "Hindu", religAll: "interCast" },
  {
    value: "Gandha Vanika",
    label: "Gandha Vanika",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Gandharb",
    label: "Gandharb",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Gandla", label: "Gandla", relig: "Hindu", religAll: "interCast" },
  {
    value: "Gandla / Ganiga",
    label: "Gandla / Ganiga",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Ganiga", label: "Ganiga", relig: "Hindu", religAll: "interCast" },
  {
    value: "Garhwali",
    label: "Garhwali",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Garo / Garoda",
    label: "Garo / Garoda",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Gatti", label: "Gatti", relig: "Hindu", religAll: "interCast" },
  { value: "Gavandi", label: "Gavandi", relig: "Hindu", religAll: "interCast" },
  { value: "Gavara", label: "Gavara", relig: "Hindu", religAll: "interCast" },
  { value: "Gavaria", label: "Gavaria", relig: "Hindu", religAll: "interCast" },
  { value: "Gawali", label: "Gawali", relig: "Hindu", religAll: "interCast" },
  { value: "Ghisadi", label: "Ghisadi", relig: "Hindu", religAll: "interCast" },
  { value: "Ghumar", label: "Ghumar", relig: "Hindu", religAll: "interCast" },
  { value: "Goala", label: "Goala", relig: "Hindu", religAll: "interCast" },
  { value: "Goan", label: "Goan", relig: "Hindu", religAll: "interCast" },
  {
    value: "Gomantak",
    label: "Gomantak",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Gond", label: "Gond", relig: "Hindu", religAll: "interCast" },
  {
    value: "Gondhali",
    label: "Gondhali",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Gopal / Gopala",
    label: "Gopal / Gopala",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Goud", label: "Goud", relig: "Hindu", religAll: "interCast" },
  { value: "Gounder", label: "Gounder", relig: "Hindu", religAll: "interCast" },
  {
    value: "Gounder - Kongu Vellala Gounder",
    label: "Gounder - Kongu Vellala Gounder",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Gounder - Nattu Gounder",
    label: "Gounder - Nattu Gounder",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Gounder - Others",
    label: "Gounder - Others",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Gounder - Urali Gounder",
    label: "Gounder - Urali Gounder",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Gounder - Vanniya Kula Kshatriyar",
    label: "Gounder - Vanniya Kula Kshatriyar",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Gounder - Vettuva Gounder",
    label: "Gounder - Vettuva Gounder",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Gowda", label: "Gowda", relig: "Hindu", religAll: "interCast" },
  {
    value: "Gowda - Kuruba Gowda",
    label: "Gowda - Kuruba Gowda",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Gramani", label: "Gramani", relig: "Hindu", religAll: "interCast" },
  { value: "Gudia", label: "Gudia", relig: "Hindu", religAll: "interCast" },
  { value: "Gujjar", label: "Gujjar", relig: "Hindu", religAll: "interCast" },
  { value: "Gulahre", label: "Gulahre", relig: "Hindu", religAll: "interCast" },
  { value: "Gupta", label: "Gupta", relig: "Hindu", religAll: "interCast" },
  { value: "Guptan", label: "Guptan", relig: "Hindu", religAll: "interCast" },
  { value: "Gurav", label: "Gurav", relig: "Hindu", religAll: "interCast" },
  { value: "Gurjar", label: "Gurjar", relig: "Hindu", religAll: "interCast" },
  {
    value: "Haihaivanshi",
    label: "Haihaivanshi",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Halba Koshti",
    label: "Halba Koshti",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Heggade", label: "Heggade", relig: "Hindu", religAll: "interCast" },
  { value: "Helava", label: "Helava", relig: "Hindu", religAll: "interCast" },
  { value: "Holar", label: "Holar", relig: "Hindu", religAll: "interCast" },
  {
    value: "Hugar (Jeer)",
    label: "Hugar (Jeer)",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Illaththu Pillai",
    label: "Illaththu Pillai",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Intrcaste",
    label: "Intercaste",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Irani", label: "Irani", relig: "Hindu", religAll: "interCast" },
  {
    value: "Isai Vellalar",
    label: "Isai Vellalar",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Jaalari", label: "Jaalari", relig: "Hindu", religAll: "interCast" },
  { value: "Jaiswal", label: "Jaiswal", relig: "Hindu", religAll: "interCast" },
  { value: "Jandra", label: "Jandra", relig: "Hindu", religAll: "interCast" },
  { value: "Jangam", label: "Jangam", relig: "Hindu", religAll: "interCast" },
  {
    value: "Jangra - Brahmin",
    label: "Jangra - Brahmin",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Jat", label: "Jat", relig: "Hindu", religAll: "interCast" },
  { value: "Jatav", label: "Jatav", relig: "Hindu", religAll: "interCast" },
  {
    value: "Jetty/Malla",
    label: "Jetty/Malla",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Jhadav", label: "Jhadav", relig: "Hindu", religAll: "interCast" },
  {
    value: "Jijhotia Brahmin",
    label: "Jijhotia Brahmin",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Jingar", label: "Jingar", relig: "Hindu", religAll: "interCast" },
  {
    value: "Jogi (Nath)",
    label: "Jogi (Nath)",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Julaha", label: "Julaha", relig: "Hindu", religAll: "interCast" },
  { value: "Kachara", label: "Kachara", relig: "Hindu", religAll: "interCast" },
  {
    value: "Kadava Patel",
    label: "Kadava Patel",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Kadia", label: "Kadia", relig: "Hindu", religAll: "interCast" },
  { value: "Kahar", label: "Kahar", relig: "Hindu", religAll: "interCast" },
  {
    value: "Kaibarta",
    label: "Kaibarta",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Kaikaala",
    label: "Kaikaala",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Kalal", label: "Kalal", relig: "Hindu", religAll: "interCast" },
  { value: "Kalanji", label: "Kalanji", relig: "Hindu", religAll: "interCast" },
  { value: "Kalar", label: "Kalar", relig: "Hindu", religAll: "interCast" },
  {
    value: "Kalbelia",
    label: "Kalbelia",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Kalinga", label: "Kalinga", relig: "Hindu", religAll: "interCast" },
  {
    value: "Kalinga Vysya",
    label: "Kalinga Vysya",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Kalita", label: "Kalita", relig: "Hindu", religAll: "interCast" },
  { value: "Kalwar", label: "Kalwar", relig: "Hindu", religAll: "interCast" },
  { value: "Kamboj", label: "Kamboj", relig: "Hindu", religAll: "interCast" },
  { value: "Kamma", label: "Kamma", relig: "Hindu", religAll: "interCast" },
  {
    value: "Kamma Naidu",
    label: "Kamma Naidu",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Kanakkan Padanna",
    label: "Kanakkan Padanna",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Kandara", label: "Kandara", relig: "Hindu", religAll: "interCast" },
  { value: "Kandera", label: "Kandera", relig: "Hindu", religAll: "interCast" },
  { value: "Kanjar", label: "Kanjar", relig: "Hindu", religAll: "interCast" },
  { value: "Kansari", label: "Kansari", relig: "Hindu", religAll: "interCast" },
  {
    value: "Kansyakaar",
    label: "Kansyakaar",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Kanykubj Bania",
    label: "Kanykubj Bania",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Kapu", label: "Kapu", relig: "Hindu", religAll: "interCast" },
  {
    value: "Kapu Naidu",
    label: "Kapu Naidu",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Kapu Reddy",
    label: "Kapu Reddy",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Karakala Bhakthula",
    label: "Karakala Bhakthula",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Karana", label: "Karana", relig: "Hindu", religAll: "interCast" },
  {
    value: "Karkathar",
    label: "Karkathar",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Karmakar",
    label: "Karmakar",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Karni Bhakthula",
    label: "Karni Bhakthula",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Karuneegar",
    label: "Karuneegar",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Kasar", label: "Kasar", relig: "Hindu", religAll: "interCast" },
  {
    value: "Kasaundhan",
    label: "Kasaundhan",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Kasera", label: "Kasera", relig: "Hindu", religAll: "interCast" },
  { value: "Kashyap", label: "Kashyap", relig: "Hindu", religAll: "interCast" },
  {
    value: "Kasukara",
    label: "Kasukara",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Katiya", label: "Katiya", relig: "Hindu", religAll: "interCast" },
  { value: "Kavara", label: "Kavara", relig: "Hindu", religAll: "interCast" },
  {
    value: "Kavuthiyya/Ezhavathy",
    label: "Kavuthiyya/Ezhavathy",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Kayastha",
    label: "Kayastha",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Kayastha (Bengali)",
    label: "Kayastha (Bengali)",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Kerala Mudali",
    label: "Kerala Mudali",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Keshri (Kesarwani)",
    label: "Keshri (Kesarwani)",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Khandayat",
    label: "Khandayat",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Khandelwal",
    label: "Khandelwal",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Kharwa", label: "Kharwa", relig: "Hindu", religAll: "interCast" },
  { value: "Kharwar", label: "Kharwar", relig: "Hindu", religAll: "interCast" },
  { value: "Khatik", label: "Khatik", relig: "Hindu", religAll: "interCast" },
  { value: "Khatri", label: "Khatri", relig: "Hindu", religAll: "interCast" },
  { value: "Kirar", label: "Kirar", relig: "Hindu", religAll: "interCast" },
  { value: "Kodava", label: "Kodava", relig: "Hindu", religAll: "interCast" },
  {
    value: "Kodikal Pillai",
    label: "Kodikal Pillai",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Kokanastha Maratha",
    label: "Kokanastha Maratha",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Kokna", label: "Kokna", relig: "Hindu", religAll: "interCast" },
  { value: "Koli", label: "Koli", relig: "Hindu", religAll: "interCast" },
  {
    value: "Koli Mahadev",
    label: "Koli Mahadev",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Koli Patel",
    label: "Koli Patel",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Komti /Arya Vaishya",
    label: "Komti /Arya Vaishya",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Kongu Chettiar",
    label: "Kongu Chettiar",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Kongu Nadar",
    label: "Kongu Nadar",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Kongu Vellala Gounder",
    label: "Kongu Vellala Gounder",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Konkani", label: "Konkani", relig: "Hindu", religAll: "interCast" },
  { value: "Korama", label: "Korama", relig: "Hindu", religAll: "interCast" },
  { value: "Kori", label: "Kori", relig: "Hindu", religAll: "interCast" },
  {
    value: "Kori/Kol",
    label: "Kori/Kol",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Kosthi", label: "Kosthi", relig: "Hindu", religAll: "interCast" },
  {
    value: "Krishnavaka",
    label: "Krishnavaka",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Kshatriya",
    label: "Kshatriya",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Kshatriya Kurmi",
    label: "Kshatriya Kurmi",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Kshatriya Raju",
    label: "Kshatriya Raju",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Kudumbi", label: "Kudumbi", relig: "Hindu", religAll: "interCast" },
  { value: "Kulal", label: "Kulal", relig: "Hindu", religAll: "interCast" },
  { value: "Kulalar", label: "Kulalar", relig: "Hindu", religAll: "interCast" },
  { value: "Kulita", label: "Kulita", relig: "Hindu", religAll: "interCast" },
  {
    value: "Kumaoni Rajput",
    label: "Kumaoni Rajput",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Kumawat", label: "Kumawat", relig: "Hindu", religAll: "interCast" },
  {
    value: "Kumbhakar",
    label: "Kumbhakar",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Kumbhar", label: "Kumbhar", relig: "Hindu", religAll: "interCast" },
  { value: "Kumhar", label: "Kumhar", relig: "Hindu", religAll: "interCast" },
  { value: "Kummari", label: "Kummari", relig: "Hindu", religAll: "interCast" },
  { value: "Kunbi", label: "Kunbi", relig: "Hindu", religAll: "interCast" },
  {
    value: "Kunbi Lonari",
    label: "Kunbi Lonari",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Kunbi Maratha",
    label: "Kunbi Maratha",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Kunbi Tirale",
    label: "Kunbi Tirale",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Kuravan", label: "Kuravan", relig: "Hindu", religAll: "interCast" },
  { value: "Kurmi", label: "Kurmi", relig: "Hindu", religAll: "interCast" },
  {
    value: "Kurmi/Kurmi Kshatriya",
    label: "Kurmi/Kurmi Kshatriya",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Kurni", label: "Kurni", relig: "Hindu", religAll: "interCast" },
  { value: "Kuruba", label: "Kuruba", relig: "Hindu", religAll: "interCast" },
  {
    value: "Kuruhina Shetty",
    label: "Kuruhina Shetty",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Kuruhini Chetty",
    label: "Kuruhini Chetty",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Kurumbar",
    label: "Kurumbar",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Kuruva", label: "Kuruva", relig: "Hindu", religAll: "interCast" },
  {
    value: "Kushwaha (Koiri)",
    label: "Kushwaha (Koiri)",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Kutchi", label: "Kutchi", relig: "Hindu", religAll: "interCast" },
  { value: "Lad", label: "Lad", relig: "Hindu", religAll: "interCast" },
  { value: "Lambadi", label: "Lambadi", relig: "Hindu", religAll: "interCast" },
  {
    value: "Laxminarayan gola",
    label: "Laxminarayan gola",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Leva patel",
    label: "Leva patel",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Leva patil",
    label: "Leva patil",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Linga Balija",
    label: "Linga Balija",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Lingayath",
    label: "Lingayath",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Lodhi Rajput",
    label: "Lodhi Rajput",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Lohana", label: "Lohana", relig: "Hindu", religAll: "interCast" },
  { value: "Lohar", label: "Lohar", relig: "Hindu", religAll: "interCast" },
  { value: "Loniya", label: "Loniya", relig: "Hindu", religAll: "interCast" },
  { value: "Lubana", label: "Lubana", relig: "Hindu", religAll: "interCast" },
  {
    value: "Madhesiya/Kanu/Halwai",
    label: "Madhesiya/Kanu/Halwai",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Madiga", label: "Madiga", relig: "Hindu", religAll: "interCast" },
  {
    value: "Madivala / Dhobi",
    label: "Madivala / Dhobi",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Mahajan", label: "Mahajan", relig: "Hindu", religAll: "interCast" },
  { value: "Mahar", label: "Mahar", relig: "Hindu", religAll: "interCast" },
  {
    value: "Mahendra",
    label: "Mahendra",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Maheshwari",
    label: "Maheshwari",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Maheshwari / Meshri",
    label: "Maheshwari / Meshri",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Mahishya",
    label: "Mahishya",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Mahor", label: "Mahor", relig: "Hindu", religAll: "interCast" },
  { value: "Mahuri", label: "Mahuri", relig: "Hindu", religAll: "interCast" },
  {
    value: "Mair Rajput Swarnkar",
    label: "Mair Rajput Swarnkar",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Majabi", label: "Majabi", relig: "Hindu", religAll: "interCast" },
  { value: "Mala", label: "Mala", relig: "Hindu", religAll: "interCast" },
  { value: "Mali", label: "Mali", relig: "Hindu", religAll: "interCast" },
  { value: "Mallah", label: "Mallah", relig: "Hindu", religAll: "interCast" },
  {
    value: "Malviya Brahmin",
    label: "Malviya Brahmin",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Malwani", label: "Malwani", relig: "Hindu", religAll: "interCast" },
  {
    value: "Mangalorean",
    label: "Mangalorean",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Manipuri",
    label: "Manipuri",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Manjapudur Chettiar",
    label: "Manjapudur Chettiar",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Mannadiyar",
    label: "Mannadiyar",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Mannan / Velan / Vannan",
    label: "Mannan / Velan / Vannan",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Mapila", label: "Mapila", relig: "Hindu", religAll: "interCast" },
  { value: "Maratha", label: "Maratha", relig: "Hindu", religAll: "interCast" },
  {
    value: "Maratha Kshatriya",
    label: "Maratha Kshatriya",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Maruthuvar",
    label: "Maruthuvar",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Matang", label: "Matang", relig: "Hindu", religAll: "interCast" },
  { value: "Mathur", label: "Mathur", relig: "Hindu", religAll: "interCast" },
  {
    value: "Mathur Vaishya",
    label: "Mathur Vaishya",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Matia Patel",
    label: "Matia Patel",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Maurya / Shakya",
    label: "Maurya / Shakya",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Meena", label: "Meena", relig: "Hindu", religAll: "interCast" },
  {
    value: "Meenavar",
    label: "Meenavar",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Meghwal", label: "Meghwal", relig: "Hindu", religAll: "interCast" },
  { value: "Mehar", label: "Mehar", relig: "Hindu", religAll: "interCast" },
  { value: "Mehra", label: "Mehra", relig: "Hindu", religAll: "interCast" },
  {
    value: "Meru Darji",
    label: "Meru Darji",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Mochi", label: "Mochi", relig: "Hindu", religAll: "interCast" },
  { value: "Modak", label: "Modak", relig: "Hindu", religAll: "interCast" },
  {
    value: "Modh Ghanchi",
    label: "Modh Ghanchi",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Modi", label: "Modi", relig: "Hindu", religAll: "interCast" },
  {
    value: "Modikarlu",
    label: "Modikarlu",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Mogaveera",
    label: "Mogaveera",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Mudiraj", label: "Mudiraj", relig: "Hindu", religAll: "interCast" },
  {
    value: "Munnuru Kapu",
    label: "Munnuru Kapu",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Musahar", label: "Musahar", relig: "Hindu", religAll: "interCast" },
  {
    value: "Musukama",
    label: "Musukama",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Muthuraja / Mutharaiyar",
    label: "Muthuraja / Mutharaiyar",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Naagavamsam",
    label: "Naagavamsam",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Nabit", label: "Nabit", relig: "Hindu", religAll: "interCast" },
  { value: "Nadar", label: "Nadar", relig: "Hindu", religAll: "interCast" },
  {
    value: "Nagaralu",
    label: "Nagaralu",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Nai / Nayi Brahmin",
    label: "Nai / Nayi Brahmin",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Naicker", label: "Naicker", relig: "Hindu", religAll: "interCast" },
  {
    value: "Naicker - Others",
    label: "Naicker - Others",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Naicker - Vanniya Kula Kshatriyar",
    label: "Naicker - Vanniya Kula Kshatriyar",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Naidu", label: "Naidu", relig: "Hindu", religAll: "interCast" },
  { value: "Naik", label: "Naik", relig: "Hindu", religAll: "interCast" },
  { value: "Nair", label: "Nair", relig: "Hindu", religAll: "interCast" },
  {
    value: "Namasudra / Namassej",
    label: "Namasudra / Namassej",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Nambiar", label: "Nambiar", relig: "Hindu", religAll: "interCast" },
  {
    value: "Namdarlu",
    label: "Namdarlu",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Nanjil Mudali",
    label: "Nanjil Mudali",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Nanjil Nattu Vellalar",
    label: "Nanjil Nattu Vellalar",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Nanjil Vellalar",
    label: "Nanjil Vellalar",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Nanjil pillai",
    label: "Nanjil pillai",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Nankudi Vellalar",
    label: "Nankudi Vellalar",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Napit", label: "Napit", relig: "Hindu", religAll: "interCast" },
  { value: "Nat", label: "Nat", relig: "Hindu", religAll: "interCast" },
  {
    value: "Nattu Gounder",
    label: "Nattu Gounder",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Nattukottai Chettiar",
    label: "Nattukottai Chettiar",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Nayaka", label: "Nayaka", relig: "Hindu", religAll: "interCast" },
  { value: "Neeli", label: "Neeli", relig: "Hindu", religAll: "interCast" },
  {
    value: "Neeli Saali",
    label: "Neeli Saali",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Nema", label: "Nema", relig: "Hindu", religAll: "interCast" },
  { value: "Nepali", label: "Nepali", relig: "Hindu", religAll: "interCast" },
  { value: "Nessi", label: "Nessi", relig: "Hindu", religAll: "interCast" },
  { value: "Nhavi", label: "Nhavi", relig: "Hindu", religAll: "interCast" },
  { value: "Niari", label: "Niari", relig: "Hindu", religAll: "interCast" },
  { value: "Odan", label: "Odan", relig: "Hindu", religAll: "interCast" },
  { value: "Ontari", label: "Ontari", relig: "Hindu", religAll: "interCast" },
  { value: "Oraon", label: "Oraon", relig: "Hindu", religAll: "interCast" },
  { value: "Oswal", label: "Oswal", relig: "Hindu", religAll: "interCast" },
  { value: "Otari", label: "Otari", relig: "Hindu", religAll: "interCast" },
  {
    value: "Othuvaar",
    label: "Othuvaar",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Padmasali",
    label: "Padmasali",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Padmashali",
    label: "Padmashali",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Padmavati Porwal",
    label: "Padmavati Porwal",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Pagadala",
    label: "Pagadala",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Pal", label: "Pal", relig: "Hindu", religAll: "interCast" },
  {
    value: "Pallan / Devandra Kula Vellalan",
    label: "Pallan / Devandra Kula Vellalan",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Panan", label: "Panan", relig: "Hindu", religAll: "interCast" },
  { value: "Panchal", label: "Panchal", relig: "Hindu", religAll: "interCast" },
  {
    value: "Pandaram",
    label: "Pandaram",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Pandiya Vellalar",
    label: "Pandiya Vellalar",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Panicker",
    label: "Panicker",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Pannirandam Chettiar",
    label: "Pannirandam Chettiar",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Paravan / Bharatar",
    label: "Paravan / Bharatar",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Parit", label: "Parit", relig: "Hindu", religAll: "interCast" },
  {
    value: "Parkavakulam / Udayar",
    label: "Parkavakulam / Udayar",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Parsi", label: "Parsi", relig: "Hindu", religAll: "interCast" },
  { value: "Partraj", label: "Partraj", relig: "Hindu", religAll: "interCast" },
  {
    value: "Parvatha Rajakulam",
    label: "Parvatha Rajakulam",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Pasi", label: "Pasi", relig: "Hindu", religAll: "interCast" },
  {
    value: "Paswan / Dusadh",
    label: "Paswan / Dusadh",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Patel", label: "Patel", relig: "Hindu", religAll: "interCast" },
  {
    value: "Pathare Prabhu",
    label: "Pathare Prabhu",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Patil", label: "Patil", relig: "Hindu", religAll: "interCast" },
  {
    value: "Patnaick/Sistakaranam",
    label: "Patnaick/Sistakaranam",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Patra", label: "Patra", relig: "Hindu", religAll: "interCast" },
  {
    value: "Pattinavar",
    label: "Pattinavar",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Pattusali",
    label: "Pattusali",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Patwa", label: "Patwa", relig: "Hindu", religAll: "interCast" },
  { value: "Perika", label: "Perika", relig: "Hindu", religAll: "interCast" },
  {
    value: "Perika/Puragiri Kshatriya",
    label: "Perika/Puragiri Kshatriya",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Pillai", label: "Pillai", relig: "Hindu", religAll: "interCast" },
  { value: "Poddar", label: "Poddar", relig: "Hindu", religAll: "interCast" },
  { value: "Poosala", label: "Poosala", relig: "Hindu", religAll: "interCast" },
  { value: "Porwal", label: "Porwal", relig: "Hindu", religAll: "interCast" },
  {
    value: "Porwal / Porwar",
    label: "Porwal / Porwar",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Poundra", label: "Poundra", relig: "Hindu", religAll: "interCast" },
  {
    value: "Prajapati",
    label: "Prajapati",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Pulaya / Cheruman",
    label: "Pulaya / Cheruman",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Rabari", label: "Rabari", relig: "Hindu", religAll: "interCast" },
  {
    value: "Radhi / Niari",
    label: "Radhi / Niari",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Raigar", label: "Raigar", relig: "Hindu", religAll: "interCast" },
  {
    value: "Rajaka / Vannar",
    label: "Rajaka / Vannar",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Rajastani",
    label: "Rajastani",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Rajbhar", label: "Rajbhar", relig: "Hindu", religAll: "interCast" },
  {
    value: "Rajbonshi",
    label: "Rajbonshi",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Rajpurohit",
    label: "Rajpurohit",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Rajput", label: "Rajput", relig: "Hindu", religAll: "interCast" },
  {
    value: "Raju / Kshatriya Raju",
    label: "Raju / Kshatriya Raju",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Ramanandi",
    label: "Ramanandi",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Ramdasia",
    label: "Ramdasia",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Ramgariah",
    label: "Ramgariah",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Ramoshi", label: "Ramoshi", relig: "Hindu", religAll: "interCast" },
  { value: "Rastogi", label: "Rastogi", relig: "Hindu", religAll: "interCast" },
  { value: "Rathi", label: "Rathi", relig: "Hindu", religAll: "interCast" },
  { value: "Rauniar", label: "Rauniar", relig: "Hindu", religAll: "interCast" },
  {
    value: "Ravana Rajput",
    label: "Ravana Rajput",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Ravidasia",
    label: "Ravidasia",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Rawat", label: "Rawat", relig: "Hindu", religAll: "interCast" },
  { value: "Reddy", label: "Reddy", relig: "Hindu", religAll: "interCast" },
  { value: "Relli", label: "Relli", relig: "Hindu", religAll: "interCast" },
  {
    value: "Rohit / Chamar",
    label: "Rohit / Chamar",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Ror", label: "Ror", relig: "Hindu", religAll: "interCast" },
  { value: "SC", label: "SC", relig: "Hindu", religAll: "interCast" },
  { value: "SKP", label: "SKP", relig: "Hindu", religAll: "interCast" },
  { value: "ST", label: "ST", relig: "Hindu", religAll: "interCast" },
  { value: "Sadgope", label: "Sadgope", relig: "Hindu", religAll: "interCast" },
  {
    value: "Sadhu Chetty",
    label: "Sadhu Chetty",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Sagara (Uppara)",
    label: "Sagara (Uppara)",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Saha", label: "Saha", relig: "Hindu", religAll: "interCast" },
  {
    value: "Sahariya",
    label: "Sahariya",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Sahu", label: "Sahu", relig: "Hindu", religAll: "interCast" },
  { value: "Saini", label: "Saini", relig: "Hindu", religAll: "interCast" },
  {
    value: "Saiva Pillai Thanjavur",
    label: "Saiva Pillai Thanjavur",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Saiva Pillai Tirunelveli",
    label: "Saiva Pillai Tirunelveli",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Saiva Vellan chettiar",
    label: "Saiva Vellan chettiar",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Saliya", label: "Saliya", relig: "Hindu", religAll: "interCast" },
  { value: "Saliya", label: "Saliya", relig: "Hindu", religAll: "interCast" },
  { value: "Salvi", label: "Salvi", relig: "Hindu", religAll: "interCast" },
  { value: "Samagar", label: "Samagar", relig: "Hindu", religAll: "interCast" },
  { value: "Sambava", label: "Sambava", relig: "Hindu", religAll: "interCast" },
  { value: "Sansi", label: "Sansi", relig: "Hindu", religAll: "interCast" },
  { value: "Sargara", label: "Sargara", relig: "Hindu", religAll: "interCast" },
  {
    value: "Sathwara",
    label: "Sathwara",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Satnami", label: "Satnami", relig: "Hindu", religAll: "interCast" },
  { value: "Savji", label: "Savji", relig: "Hindu", religAll: "interCast" },
  {
    value: "Senai Thalaivar",
    label: "Senai Thalaivar",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Senguntha Mudaliyar",
    label: "Senguntha Mudaliyar",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Sengunthar/Kaikolar",
    label: "Sengunthar/Kaikolar",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Settibalija",
    label: "Settibalija",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Setty Balija",
    label: "Setty Balija",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Shah", label: "Shah", relig: "Hindu", religAll: "interCast" },
  {
    value: "Shaw / Sahu/Teli",
    label: "Shaw / Sahu/Teli",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Shettigar",
    label: "Shettigar",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Shilpkar",
    label: "Shilpkar",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Shimpi/Namdev",
    label: "Shimpi/Namdev",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Sindhi", label: "Sindhi", relig: "Hindu", religAll: "interCast" },
  {
    value: "Sindhi-Amil",
    label: "Sindhi-Amil",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Sindhi-Baibhand",
    label: "Sindhi-Baibhand",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Sindhi-Bhanusali",
    label: "Sindhi-Bhanusali",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Sindhi-Bhatia",
    label: "Sindhi-Bhatia",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Sindhi-Chhapru",
    label: "Sindhi-Chhapru",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Sindhi-Dadu",
    label: "Sindhi-Dadu",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Sindhi-Hyderabadi",
    label: "Sindhi-Hyderabadi",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Sindhi-Larai",
    label: "Sindhi-Larai",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Sindhi-Larkana",
    label: "Sindhi-Larkana",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Sindhi-Lohana",
    label: "Sindhi-Lohana",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Sindhi-Rohiri",
    label: "Sindhi-Rohiri",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Sindhi-Sahiti",
    label: "Sindhi-Sahiti",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Sindhi-Sakkhar",
    label: "Sindhi-Sakkhar",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Sindhi-Sehwani",
    label: "Sindhi-Sehwani",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Sindhi-Shikarpuri",
    label: "Sindhi-Shikarpuri",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Sindhi-Thatai",
    label: "Sindhi-Thatai",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Sirvi / Janwa",
    label: "Sirvi / Janwa",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Sonar", label: "Sonar", relig: "Hindu", religAll: "interCast" },
  { value: "Sondhia", label: "Sondhia", relig: "Hindu", religAll: "interCast" },
  { value: "Soni", label: "Soni", relig: "Hindu", religAll: "interCast" },
  { value: "Sonkar", label: "Sonkar", relig: "Hindu", religAll: "interCast" },
  {
    value: "Sourashtra",
    label: "Sourashtra",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Sozhia Chetty",
    label: "Sozhia Chetty",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Sozhiya Vellalar",
    label: "Sozhiya Vellalar",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Srisayana",
    label: "Srisayana",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Sugali (Naika)",
    label: "Sugali (Naika)",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Sunari", label: "Sunari", relig: "Hindu", religAll: "interCast" },
  { value: "Sundhi", label: "Sundhi", relig: "Hindu", religAll: "interCast" },
  {
    value: "Surya Balija",
    label: "Surya Balija",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Suthar", label: "Suthar", relig: "Hindu", religAll: "interCast" },
  {
    value: "Swakula Saali",
    label: "Swakula Saali",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Swakula Sali",
    label: "Swakula Sali",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Swarnakar",
    label: "Swarnakar",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Tamboli", label: "Tamboli", relig: "Hindu", religAll: "interCast" },
  { value: "Tammali", label: "Tammali", relig: "Hindu", religAll: "interCast" },
  { value: "Tanti", label: "Tanti", relig: "Hindu", religAll: "interCast" },
  {
    value: "Tantubai",
    label: "Tantubai",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Telaga", label: "Telaga", relig: "Hindu", religAll: "interCast" },
  { value: "Teli", label: "Teli", relig: "Hindu", religAll: "interCast" },
  {
    value: "Telugupatti",
    label: "Telugupatti",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Thakkar", label: "Thakkar", relig: "Hindu", religAll: "interCast" },
  { value: "Thakore", label: "Thakore", relig: "Hindu", religAll: "interCast" },
  { value: "Thakur", label: "Thakur", relig: "Hindu", religAll: "interCast" },
  { value: "Thandan", label: "Thandan", relig: "Hindu", religAll: "interCast" },
  {
    value: "Tharakan",
    label: "Tharakan",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Thigala", label: "Thigala", relig: "Hindu", religAll: "interCast" },
  { value: "Thiyya", label: "Thiyya", relig: "Hindu", religAll: "interCast" },
  {
    value: "Thiyya Thandan",
    label: "Thiyya Thandan",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Thogata Veera Kshatriya",
    label: "Thogata Veera Kshatriya",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Thogata Veerakshathriya",
    label: "Thogata Veerakshathriya",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Thondai Mandala Vellalar",
    label: "Thondai Mandala Vellalar",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Thota", label: "Thota", relig: "Hindu", religAll: "interCast" },
  { value: "Tili", label: "Tili", relig: "Hindu", religAll: "interCast" },
  {
    value: "Tiyar/Tiar",
    label: "Tiyar/Tiar",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Togata", label: "Togata", relig: "Hindu", religAll: "interCast" },
  {
    value: "Tonk Kshatriya",
    label: "Tonk Kshatriya",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Turupu Kapu",
    label: "Turupu Kapu",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Ummar / Umre / Bagaria",
    label: "Ummar / Umre / Bagaria",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Urali Gounder",
    label: "Urali Gounder",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Urs", label: "Urs", relig: "Hindu", religAll: "interCast" },
  {
    value: "Vada Balija",
    label: "Vada Balija",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Vadambar",
    label: "Vadambar",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Vadar", label: "Vadar", relig: "Hindu", religAll: "interCast" },
  { value: "Vaddera", label: "Vaddera", relig: "Hindu", religAll: "interCast" },
  { value: "Vadugan", label: "Vadugan", relig: "Hindu", religAll: "interCast" },
  { value: "Vaish", label: "Vaish", relig: "Hindu", religAll: "interCast" },
  {
    value: "Vaishnav",
    label: "Vaishnav",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Vaishnav Dishaval",
    label: "Vaishnav Dishaval",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Vaishnav Kapol",
    label: "Vaishnav Kapol",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Vaishnav Khadyata",
    label: "Vaishnav Khadyata",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Vaishnav Lad",
    label: "Vaishnav Lad",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Vaishnav Modh",
    label: "Vaishnav Modh",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Vaishnav Porvad",
    label: "Vaishnav Porvad",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Vaishnav Shrimali",
    label: "Vaishnav Shrimali",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Vaishnav Sorathaiya",
    label: "Vaishnav Sorathaiya",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Vaishnav Vania",
    label: "Vaishnav Vania",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Vaishnava",
    label: "Vaishnava",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Vaishya", label: "Vaishya", relig: "Hindu", religAll: "interCast" },
  {
    value: "Vaishya Vani",
    label: "Vaishya Vani",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Valar", label: "Valar", relig: "Hindu", religAll: "interCast" },
  {
    value: "Valluvan",
    label: "Valluvan",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Valmiki", label: "Valmiki", relig: "Hindu", religAll: "interCast" },
  { value: "Valsad", label: "Valsad", relig: "Hindu", religAll: "interCast" },
  { value: "Vani", label: "Vani", relig: "Hindu", religAll: "interCast" },
  {
    value: "Vani / Vaishya",
    label: "Vani / Vaishya",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Vania", label: "Vania", relig: "Hindu", religAll: "interCast" },
  {
    value: "Vanika Vyshya",
    label: "Vanika Vyshya",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Vaniya", label: "Vaniya", relig: "Hindu", religAll: "interCast" },
  {
    value: "Vaniya Chettiar",
    label: "Vaniya Chettiar",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Vanjara", label: "Vanjara", relig: "Hindu", religAll: "interCast" },
  { value: "Vanjari", label: "Vanjari", relig: "Hindu", religAll: "interCast" },
  { value: "Vankar", label: "Vankar", relig: "Hindu", religAll: "interCast" },
  { value: "Vannar", label: "Vannar", relig: "Hindu", religAll: "interCast" },
  {
    value: "Vannia Kula Kshatriyar",
    label: "Vannia Kula Kshatriyar",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Vanyakulakshatriya",
    label: "Vanyakulakshatriya",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Variar", label: "Variar", relig: "Hindu", religAll: "interCast" },
  {
    value: "Varshney",
    label: "Varshney",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Varshney (Barahseni)",
    label: "Varshney (Barahseni)",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Veera Saivam",
    label: "Veera Saivam",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Veerakodi Vellala",
    label: "Veerakodi Vellala",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Velaan", label: "Velaan", relig: "Hindu", religAll: "interCast" },
  { value: "Velama", label: "Velama", relig: "Hindu", religAll: "interCast" },
  {
    value: "Vellala Pillai",
    label: "Vellala Pillai",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Vellalar",
    label: "Vellalar",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Vellan Chettiars",
    label: "Vellan Chettiars",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Veluthedathu Nair",
    label: "Veluthedathu Nair",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Vettuva Gounder",
    label: "Vettuva Gounder",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Vettuvan",
    label: "Vettuvan",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Vijayvargia",
    label: "Vijayvargia",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Vilakithala Nair",
    label: "Vilakithala Nair",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Vilakkithala Nair",
    label: "Vilakkithala Nair",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Vishwakarma",
    label: "Vishwakarma",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Viswabrahmin",
    label: "Viswabrahmin",
    relig: "Hindu",
    religAll: "interCast",
  },
  {
    value: "Vokkaliga",
    label: "Vokkaliga",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Vysya", label: "Vysya", relig: "Hindu", religAll: "interCast" },
  { value: "Yadav", label: "Yadav", relig: "Hindu", religAll: "interCast" },
  {
    value: "Yadava Naidu",
    label: "Yadava Naidu",
    relig: "Hindu",
    religAll: "interCast",
  },
  { value: "Yellapu", label: "Yellapu", relig: "Hindu", religAll: "interCast" },

  {
    value: "Muslim - Any",
    label: "Muslim - Any",
    relig: "Muslim",
    religAll: "interCast",
  },
  {
    value: "Muslim - Ansari",
    label: "Muslim - Ansari",
    relig: "Muslim",
    religAll: "interCast",
  },
  {
    value: "Muslim - Arain",
    label: "Muslim - Arain",
    relig: "Muslim",
    religAll: "interCast",
  },
  {
    value: "Muslim - Awan",
    label: "Muslim - Awan",
    relig: "Muslim",
    religAll: "interCast",
  },
  {
    value: "Muslim - Bohra",
    label: "Muslim - Bohra",
    relig: "Muslim",
    religAll: "interCast",
  },
  {
    value: "Muslim - Dekkani",
    label: "Muslim - Dekkani",
    relig: "Muslim",
    religAll: "interCast",
  },
  {
    value: "Muslim - Dudekula",
    label: "Muslim - Dudekula",
    relig: "Muslim",
    religAll: "interCast",
  },
  {
    value: "Muslim - Hanafi",
    label: "Muslim - Hanafi",
    relig: "Muslim",
    religAll: "interCast",
  },
  {
    value: "Muslim - Jat",
    label: "Muslim - Jat",
    relig: "Muslim",
    religAll: "interCast",
  },
  {
    value: "Muslim - Khoja",
    label: "Muslim - Khoja",
    relig: "Muslim",
    religAll: "interCast",
  },
  {
    value: "Muslim - Lebbai",
    label: "Muslim - Lebbai",
    relig: "Muslim",
    religAll: "interCast",
  },
  {
    value: "Muslim - Malik",
    label: "Muslim - Malik",
    relig: "Muslim",
    religAll: "interCast",
  },
  {
    value: "Muslim - Mapila",
    label: "Muslim - Mapila",
    relig: "Muslim",
    religAll: "interCast",
  },
  {
    value: "Muslim - Maraicar",
    label: "Muslim - Maraicar",
    relig: "Muslim",
    religAll: "interCast",
  },
  {
    value: "Muslim - Memon",
    label: "Muslim - Memon",
    relig: "Muslim",
    religAll: "interCast",
  },
  {
    value: "Muslim - Mughal",
    label: "Muslim - Mughal",
    relig: "Muslim",
    religAll: "interCast",
  },
  {
    value: "Muslim - Others",
    label: "Muslim - Others",
    relig: "Muslim",
    religAll: "interCast",
  },
  {
    value: "Muslim - Pathan",
    label: "Muslim - Pathan",
    relig: "Muslim",
    religAll: "interCast",
  },
  {
    value: "Muslim - Qureshi",
    label: "Muslim - Qureshi",
    relig: "Muslim",
    religAll: "interCast",
  },
  {
    value: "Muslim - Rajput",
    label: "Muslim - Rajput",
    relig: "Muslim",
    religAll: "interCast",
  },
  {
    value: "Muslim - Rowther",
    label: "Muslim - Rowther",
    relig: "Muslim",
    religAll: "interCast",
  },
  {
    value: "Muslim - Shafi",
    label: "Muslim - Shafi",
    relig: "Muslim",
    religAll: "interCast",
  },
  {
    value: "Muslim - Sheikh",
    label: "Muslim - Sheikh",
    relig: "Muslim",
    religAll: "interCast",
  },
  {
    value: "Muslim - Siddiqui",
    label: "Muslim - Siddiqui",
    relig: "Muslim",
    religAll: "interCast",
  },
  {
    value: "Muslim - Syed",
    label: "Muslim - Syed",
    relig: "Muslim",
    religAll: "interCast",
  },
  {
    value: "Muslim - UnSpecified",
    label: "Muslim - UnSpecified",
    relig: "Muslim",
    religAll: "interCast",
  },

  {
    value: "Christian - Any",
    label: "Christian - Any",
    relig: "Christian",
    religAll: "interCast",
  },
  {
    value: "Adventist",
    label: "Adventist",
    relig: "Christian",
    religAll: "interCast",
  },
  {
    value: "Anglican / Episcopal",
    label: "Anglican / Episcopal",
    relig: "Christian",
    religAll: "interCast",
  },
  {
    value: "Anglo-Indian",
    label: "Anglo-Indian",
    relig: "Christian",
    religAll: "interCast",
  },
  {
    value: "Apostolic",
    label: "Apostolic",
    relig: "Christian",
    religAll: "interCast",
  },
  {
    value: "Assembly of God (AG)",
    label: "Assembly of God (AG)",
    relig: "Christian",
    religAll: "interCast",
  },
  {
    value: "Baptist",
    label: "Baptist",
    relig: "Christian",
    religAll: "interCast",
  },
  {
    value: "Born Again",
    label: "Born Again",
    relig: "Christian",
    religAll: "interCast",
  },
  {
    value: "Brethren",
    label: "Brethren",
    relig: "Christian",
    religAll: "interCast",
  },
  {
    value: "Calvinist",
    label: "Calvinist",
    relig: "Christian",
    religAll: "interCast",
  },
  {
    value: "Chaldean Syrian (Assyrian)",
    label: "Chaldean Syrian (Assyrian)",
    relig: "Christian",
    religAll: "interCast",
  },
  {
    value: "Church of Christ",
    label: "Church of Christ",
    relig: "Christian",
    religAll: "interCast",
  },
  {
    value: "Church of God",
    label: "Church of God",
    relig: "Christian",
    religAll: "interCast",
  },
  {
    value: "Church of North India",
    label: "Church of North India",
    relig: "Christian",
    religAll: "interCast",
  },
  {
    value: "Church of South India",
    label: "Church of South India",
    relig: "Christian",
    religAll: "interCast",
  },
  {
    value: "Congregational",
    label: "Congregational",
    relig: "Christian",
    religAll: "interCast",
  },
  {
    value: "Evangelist",
    label: "Evangelist",
    relig: "Christian",
    religAll: "interCast",
  },
  {
    value: "Jacobite",
    label: "Jacobite",
    relig: "Christian",
    religAll: "interCast",
  },
  {
    value: "Jehovah's Witnesses",
    label: "Jehovah's Witnesses",
    relig: "Christian",
    religAll: "interCast",
  },
  {
    value: "Knanaya",
    label: "Knanaya",
    relig: "Christian",
    religAll: "interCast",
  },
  {
    value: "Knanaya Catholic",
    label: "Knanaya Catholic",
    relig: "Christian",
    religAll: "interCast",
  },
  {
    value: "Knanaya Jacobit",
    label: "Knanaya Jacobit",
    relig: "Christian",
    religAll: "interCast",
  },
  {
    value: "Latin Catholic",
    label: "Latin Catholic",
    relig: "Christian",
    religAll: "interCast",
  },
  {
    value: "Latter day saints",
    label: "Latter day saints",
    relig: "Christian",
    religAll: "interCast",
  },
  {
    value: "Lutheran",
    label: "Lutheran",
    relig: "Christian",
    religAll: "interCast",
  },
  {
    value: "Malabar Independent Syrian Church",
    label: "Malabar Independent Syrian Church",
    relig: "Christian",
    religAll: "interCast",
  },
  {
    value: "Malankara catholic",
    label: "Malankara catholic",
    relig: "Christian",
    religAll: "interCast",
  },
  {
    value: "Marthoma",
    label: "Marthoma",
    relig: "Christian",
    religAll: "interCast",
  },
  {
    value: "Melkite",
    label: "Melkite",
    relig: "Christian",
    religAll: "interCast",
  },
  {
    value: "Mennonite",
    label: "Mennonite",
    relig: "Christian",
    religAll: "interCast",
  },
  {
    value: "Methodist",
    label: "Methodist",
    relig: "Christian",
    religAll: "interCast",
  },
  {
    value: "Moravian",
    label: "Moravian",
    relig: "Christian",
    religAll: "interCast",
  },
  {
    value: "Orthodox",
    label: "Orthodox",
    relig: "Christian",
    religAll: "interCast",
  },
  {
    value: "Others",
    label: "Others",
    relig: "Christian",
    religAll: "interCast",
  },
  {
    value: "Pentecost",
    label: "Pentecost",
    relig: "Christian",
    religAll: "interCast",
  },
  {
    value: "Presbyterian",
    label: "Presbyterian",
    relig: "Christian",
    religAll: "interCast",
  },
  {
    value: "Protestant",
    label: "Protestant",
    relig: "Christian",
    religAll: "interCast",
  },
  {
    value: "Reformed Baptist",
    label: "Reformed Baptist",
    relig: "Christian",
    religAll: "interCast",
  },
  {
    value: "Reformed Presbyterian",
    label: "Reformed Presbyterian",
    relig: "Christian",
    religAll: "interCast",
  },
  {
    value: "Roman Catholic",
    label: "Roman Catholic",
    relig: "Christian",
    religAll: "interCast",
  },
  {
    value: "Seventh-day Adventist",
    label: "Seventh-day Adventist",
    relig: "Christian",
    religAll: "interCast",
  },
  {
    value: "St. Thomas Evangelical",
    label: "St. Thomas Evangelical",
    relig: "Christian",
    religAll: "interCast",
  },
  {
    value: "Syrian Catholic",
    label: "Syrian Catholic",
    relig: "Christian",
    religAll: "interCast",
  },
  {
    value: "Syrian Jacobite",
    label: "Syrian Jacobite",
    relig: "Christian",
    religAll: "interCast",
  },
  {
    value: "Syrian Orthodox",
    label: "Syrian Orthodox",
    relig: "Christian",
    religAll: "interCast",
  },
  {
    value: "Syro Malabar",
    label: "Syro Malabar",
    relig: "Christian",
    religAll: "interCast",
  },

  {
    value: "Sikh - Any",
    label: "Sikh - Any",
    relig: "Sikh",
    religAll: "interCast",
  },
  {
    value: "Sikh - Ahluwalia",
    label: "Sikh - Ahluwalia",
    relig: "Sikh",
    religAll: "interCast",
  },
  {
    value: "Sikh - Arora",
    label: "Sikh - Arora",
    relig: "Sikh",
    religAll: "interCast",
  },
  {
    value: "Sikh - Bhatia",
    label: "Sikh - Bhatia",
    relig: "Sikh",
    religAll: "interCast",
  },
  {
    value: "Sikh - Bhatra",
    label: "Sikh - Bhatra",
    relig: "Sikh",
    religAll: "interCast",
  },
  {
    value: "Sikh - Ghumar",
    label: "Sikh - Ghumar",
    relig: "Sikh",
    religAll: "interCast",
  },
  {
    value: "Sikh - Intercaste",
    label: "Sikh - Intercaste",
    relig: "Sikh",
    religAll: "interCast",
  },
  {
    value: "Sikh - Jat",
    label: "Sikh - Jat",
    relig: "Sikh",
    religAll: "interCast",
  },
  {
    value: "Sikh - Kamboj",
    label: "Sikh - Kamboj",
    relig: "Sikh",
    religAll: "interCast",
  },
  {
    value: "Sikh - Khatri",
    label: "Sikh - Khatri",
    relig: "Sikh",
    religAll: "interCast",
  },
  {
    value: "Sikh - Kshatriya",
    label: "Sikh - Kshatriya",
    relig: "Sikh",
    religAll: "interCast",
  },
  {
    value: "Sikh - Lubana",
    label: "Sikh - Lubana",
    relig: "Sikh",
    religAll: "interCast",
  },
  {
    value: "Sikh - Majabi",
    label: "Sikh - Majabi",
    relig: "Sikh",
    religAll: "interCast",
  },
  {
    value: "Sikh - Nai",
    label: "Sikh - Nai",
    relig: "Sikh",
    religAll: "interCast",
  },
  {
    value: "Sikh - Others",
    label: "Sikh - Others",
    relig: "Sikh",
    religAll: "interCast",
  },
  {
    value: "Sikh - Rai",
    label: "Sikh - Rai",
    relig: "Sikh",
    religAll: "interCast",
  },
  {
    value: "Sikh - Rajput",
    label: "Sikh - Rajput",
    relig: "Sikh",
    religAll: "interCast",
  },
  {
    value: "Sikh - Ramdasia",
    label: "Sikh - Ramdasia",
    relig: "Sikh",
    religAll: "interCast",
  },
  {
    value: "Sikh - Ramgharia",
    label: "Sikh - Ramgharia",
    relig: "Sikh",
    religAll: "interCast",
  },
  {
    value: "Sikh - Ravidasia",
    label: "Sikh - Ravidasia",
    relig: "Sikh",
    religAll: "interCast",
  },
  {
    value: "Sikh - Saini",
    label: "Sikh - Saini",
    relig: "Sikh",
    religAll: "interCast",
  },
  {
    value: "Sikh - Tonk Kshatriya",
    label: "Sikh - Tonk Kshatriya",
    relig: "Sikh",
    religAll: "interCast",
  },
  {
    value: "Sikh - Unspecified",
    label: "Sikh - Unspecified",
    relig: "Sikh",
    religAll: "interCast",
  },

  {
    value: "Jain - Any",
    label: "Jain - Any",
    relig: "Jain",
    religAll: "interCast",
  },
  {
    value: "Jain - Agarwal",
    label: "Jain - Agarwal",
    relig: "Jain",
    religAll: "interCast",
  },
  {
    value: "Jain - Asati",
    label: "Jain - Asati",
    relig: "Jain",
    religAll: "interCast",
  },
  {
    value: "Jain - Ayodhyavasi",
    label: "Jain - Ayodhyavasi",
    relig: "Jain",
    religAll: "interCast",
  },
  {
    value: "Jain - Bagherwal",
    label: "Jain - Bagherwal",
    relig: "Jain",
    religAll: "interCast",
  },
  {
    value: "Jain - Bania",
    label: "Jain - Bania",
    relig: "Jain",
    religAll: "interCast",
  },
  {
    value: "Jain - Barhiya",
    label: "Jain - Barhiya",
    relig: "Jain",
    religAll: "interCast",
  },
  {
    value: "Jain - Charanagare",
    label: "Jain - Charanagare",
    relig: "Jain",
    religAll: "interCast",
  },
  {
    value: "Jain - Chaturtha",
    label: "Jain - Chaturtha",
    relig: "Jain",
    religAll: "interCast",
  },
  {
    value: "Jain - Dhakada",
    label: "Jain - Dhakada",
    relig: "Jain",
    religAll: "interCast",
  },
  {
    value: "Jain - Gahoi / Grihapati",
    label: "Jain - Gahoi / Grihapati",
    relig: "Jain",
    religAll: "interCast",
  },
  {
    value: "Jain - Golalare / Kharaua",
    label: "Jain - Golalare / Kharaua",
    relig: "Jain",
    religAll: "interCast",
  },
  {
    value: "Jain - Golapurva",
    label: "Jain - Golapurva",
    relig: "Jain",
    religAll: "interCast",
  },
  {
    value: "Jain - Golsinghare",
    label: "Jain - Golsinghare",
    relig: "Jain",
    religAll: "interCast",
  },
  {
    value: "Jain - Harada",
    label: "Jain - Harada",
    relig: "Jain",
    religAll: "interCast",
  },
  {
    value: "Jain - Humad / Humbad",
    label: "Jain - Humad / Humbad",
    relig: "Jain",
    religAll: "interCast",
  },
  {
    value: "Jain - Intercaste",
    label: "Jain - Intercaste",
    relig: "Jain",
    religAll: "interCast",
  },
  {
    value: "Jain - Jaiswal",
    label: "Jain - Jaiswal",
    relig: "Jain",
    religAll: "interCast",
  },
  {
    value: "Jain - KVO",
    label: "Jain - KVO",
    relig: "Jain",
    religAll: "interCast",
  },
  {
    value: "Jain - Kambhoja",
    label: "Jain - Kambhoja",
    relig: "Jain",
    religAll: "interCast",
  },
  {
    value: "Jain - Kasar",
    label: "Jain - Kasar",
    relig: "Jain",
    religAll: "interCast",
  },
  {
    value: "Jain - Kathanere",
    label: "Jain - Kathanere",
    relig: "Jain",
    religAll: "interCast",
  },
  {
    value: "Jain - Khandelwal",
    label: "Jain - Khandelwal",
    relig: "Jain",
    religAll: "interCast",
  },
  {
    value: "Jain - Kharaua",
    label: "Jain - Kharaua",
    relig: "Jain",
    religAll: "interCast",
  },
  {
    value: "Jain - Kutchi",
    label: "Jain - Kutchi",
    relig: "Jain",
    religAll: "interCast",
  },
  {
    value: "Jain - Lamechu",
    label: "Jain - Lamechu",
    relig: "Jain",
    religAll: "interCast",
  },
  {
    value: "Jain - Nema",
    label: "Jain - Nema",
    relig: "Jain",
    religAll: "interCast",
  },
  {
    value: "Jain - Oswal",
    label: "Jain - Oswal",
    relig: "Jain",
    religAll: "interCast",
  },
  {
    value: "Jain - Others",
    label: "Jain - Others",
    relig: "Jain",
    religAll: "interCast",
  },
  {
    value: "Jain - Padmavati Porwal",
    label: "Jain - Padmavati Porwal",
    relig: "Jain",
    religAll: "interCast",
  },
  {
    value: "Jain - Palliwal",
    label: "Jain - Palliwal",
    relig: "Jain",
    religAll: "interCast",
  },
  {
    value: "Jain - Panchama",
    label: "Jain - Panchama",
    relig: "Jain",
    religAll: "interCast",
  },
  {
    value: "Jain - Parmar",
    label: "Jain - Parmar",
    relig: "Jain",
    religAll: "interCast",
  },
  {
    value: "Jain - Parwar / Paravara",
    label: "Jain - Parwar / Paravara",
    relig: "Jain",
    religAll: "interCast",
  },
  {
    value: "Jain - Porwad / Porwal",
    label: "Jain - Porwad / Porwal",
    relig: "Jain",
    religAll: "interCast",
  },
  {
    value: "Jain - Porwal",
    label: "Jain - Porwal",
    relig: "Jain",
    religAll: "interCast",
  },
  {
    value: "Jain - Saitwal",
    label: "Jain - Saitwal",
    relig: "Jain",
    religAll: "interCast",
  },
  {
    value: "Jain - Samanar / Nayinar",
    label: "Jain - Samanar / Nayinar",
    relig: "Jain",
    religAll: "interCast",
  },
  {
    value: "Jain - Samiya",
    label: "Jain - Samiya",
    relig: "Jain",
    religAll: "interCast",
  },
  {
    value: "Jain - Sarak",
    label: "Jain - Sarak",
    relig: "Jain",
    religAll: "interCast",
  },
  {
    value: "Jain - Shrimal",
    label: "Jain - Shrimal",
    relig: "Jain",
    religAll: "interCast",
  },
  {
    value: "Jain - Upadhyaya",
    label: "Jain - Upadhyaya",
    relig: "Jain",
    religAll: "interCast",
  },
  {
    value: "Jain - Vaishya",
    label: "Jain - Vaishya",
    relig: "Jain",
    religAll: "interCast",
  },
  {
    value: "Jain - Veerwal",
    label: "Jain - Veerwal",
    relig: "Jain",
    religAll: "interCast",
  },

  {
    value: "Parsi - Any",
    label: "Parsi - Any",
    relig: "Parsi",
    religAll: "interCast",
  },
  { value: "Irani", label: "Irani", relig: "Parsi", religAll: "interCast" },
  { value: "Parsi", label: "Parsi", relig: "Parsi", religAll: "interCast" },
  {
    value: "Caste no bar",
    label: "Caste no bar",
    relig: "Parsi",
    religAll: "interCast",
  },

  {
    value: "Buddhist - Any",
    label: "Buddhist - Any",
    relig: "Buddhist",
    religAll: "interCast",
  },
  {
    value: "Neo Buddhist",
    label: "Neo Buddhist",
    relig: "Buddhist",
    religAll: "interCast",
  },
  {
    value: "Others",
    label: "Others",
    relig: "Buddhist",
    religAll: "interCast",
  },
  {
    value: "Tibetan Buddhist",
    label: "Tibetan Buddhist",
    relig: "Buddhist",
    religAll: "interCast",
  },

  {
    value: "Jewish - Any",
    label: "Jewish - Any",
    relig: "Jewish",
    religAll: "interCast",
  },
  {
    value: "Caste no bar",
    label: "Caste no bar",
    relig: "Jewish",
    religAll: "interCast",
  },

  {
    value: "Inter Religion",
    label: "Inter Religion",
    relig: "Inter Religion",
    religAll: "interCast",
  },
  {
    value: "Any",
    label: "Any",
    relig: "Inter Religion",
    religAll: "interCast",
  },
];
