export const favFoodOptions = [
  { value: "American", label: "American" },
  { value: "Arabic", label: "Arabic" },
  { value: "Bengali", label: "Bengali" },
  { value: "Brazilian", label: "Brazilian" },
  { value: "Chinese", label: "Chinese" },
  { value: "Continental", label: "Continental" },
  { value: "Ethiopian", label: "Ethiopian" },
  { value: "Fast food", label: "Fast food" },
  { value: "French", label: "French" },
  { value: "Greek", label: "Greek" },
  { value: "Gujarati", label: "Gujarati" },
  { value: "Italian", label: "Italian" },
  { value: "Japanese", label: "Japanese" },
  { value: "Konkan", label: "Konkan" },
  { value: "Korean", label: "Korean" },
  { value: "Lebanese", label: "Lebanese" },
  { value: "Malaysian", label: "Malaysian" },
  { value: "Marathi", label: "Marathi" },
  { value: "Mediterranean", label: "Mediterranean" },
  { value: "Mexican", label: "Mexican" },

  { value: "Mughlai", label: "Mughlai" },
  { value: "North Indian", label: "North Indian" },
  { value: "Odia", label: "Odia" },
  { value: "Oriental", label: "Oriental" },
  { value: "Parsi", label: "Parsi" },
  { value: "Punjabi", label: "Punjabi" },
  { value: "Rajasthani", label: "Rajasthani" },
  { value: "Soul Food", label: "Soul Food" },
  { value: "South Indian", label: "South Indian" },
  { value: "Spanish", label: "Spanish" },
  { value: "Srilankan", label: "Srilankan" },
  { value: "Thai", label: "Thai" },
  { value: "Turkish", label: "Turkish" },
];
export const hobbiesOptions = [
  { value: "Acting", label: "Acting" },
  { value: "Adventure sports", label: "Adventure sports" },
  {
    value: "Alternative healing / Medicine",
    label: "Alternative healing / Medicine",
  },
  { value: "Art / Handicraft", label: "Art / Handicraft" },
  { value: "Astrology", label: "Astrology" },
  { value: "Baking", label: "Baking" },
  { value: "Bike / Car enthusiast", label: "Bike / Car enthusiast" },
  { value: "Bird watching", label: "Bird watching" },
  { value: "Blogging / Video blogging", label: "Blogging / Video blogging" },
  { value: "Board games", label: "Board games" },
  { value: "Book clubs", label: "Book clubs" },
  { value: "Calligraphy", label: "Calligraphy" },
  { value: "Clubbing", label: "Clubbing" },
  { value: "Collectibles", label: "Collectibles" },
  { value: "Cooking", label: "Cooking" },
  { value: "Crosswords", label: "Crosswords" },
  { value: "Dancing", label: "Dancing" },
  {
    value: "DIY (Do it yourself) projects",
    label: "DIY (Do it yourself) projects",
  },
  { value: "Fashion design", label: "Fashion design" },
  { value: "Film-making", label: "Film-making" },
  { value: "Fishing", label: "Fishing" },
  { value: "Gardening / Landscaping", label: "Gardening / Landscaping" },
  { value: "Going on long drives", label: "Going on long drives" },
  { value: "Ham radio", label: "Ham radio" },
  { value: "Home / Interior decoration", label: "Home / Interior decoration" },
  { value: "Learning new languages", label: "Learning new languages" },
  { value: "Listening to podcasts", label: "Listening to podcasts" },
  { value: "Mimicry", label: "Mimicry" },
  {
    value: "Museums / Galleries / Exhibitions",
    label: "Museums / Galleries / Exhibitions",
  },
  { value: "Numerology", label: "Numerology" },
  {
    value: "Painting / Sketching / Drawing",
    label: "Painting / Sketching / Drawing",
  },
  { value: "Palmistry", label: "Palmistry" },
  { value: "Pets", label: "Pets" },
  { value: "Photography", label: "Photography" },
  { value: "Playing cards", label: "Playing cards" },
  {
    value: "Playing musical instruments",
    label: "Playing musical instruments",
  },
  { value: "Politics", label: "Politics" },
  { value: "Scrabble", label: "Scrabble" },
  { value: "Shopping", label: "Shopping" },
  { value: "Sightseeing", label: "Sightseeing" },
  { value: "Singing", label: "Singing" },
  { value: "Social media", label: "Social media" },
  { value: "Social service", label: "Social service" },
  { value: "Solving Puzzles", label: "Solving Puzzles" },
  { value: "Stargazing", label: "Stargazing" },
  { value: "Stitching", label: "Stitching" },
  { value: "Tailoring", label: "Tailoring" },
  { value: "Technology", label: "Technology" },
  { value: "Travel", label: "Travel" },
  { value: "Tutoring", label: "Tutoring" },
  { value: "Video / Computer Gaming", label: "Video / Computer Gaming" },
  { value: "Volunteer Work", label: "Volunteer Work" },
  { value: "Wine tasting", label: "Wine tasting" },
  { value: "Writing", label: "Writing" },
];
export const musicOptions = [
  { value: "Bhangra", label: "Bhangra" },
  { value: "Bluegrass", label: "Bluegrass" },
  { value: "Blues", label: "Blues" },
  { value: "Christian / Gospel", label: "Christian / Gospel" },
  { value: "Classical", label: "Classical" },
  { value: "Classical - Carnatic", label: "Classical - Carnatic" },
  { value: "Country", label: "Country" },
  { value: "Death metal", label: "Death metal" },
  { value: "Devotional", label: "Devotional" },
  { value: "Disco", label: "Disco" },
  {
    value: "EDM (Electronic Dance Music)",
    label: "EDM (Electronic Dance Music)",
  },
  { value: "Film songs", label: "Film songs" },
  { value: "Folk music", label: "Folk music" },
  { value: "Fusion", label: "Fusion" },
  { value: "Ghazals", label: "Ghazals" },
  { value: "Heavy metal", label: "Heavy metal" },
  { value: "Hip-Hop", label: "Hip-Hop" },
  { value: "House music", label: "House music" },
  { value: "Indian / Hindustan", label: "Indian / Hindustan" },
  { value: "Indie Rock", label: "Indie Rock" },
  { value: "Indipop", label: "Indipop" },
  { value: "Jazz", label: "Jazz" },
  { value: "K-pop", label: "K-pop" },
  { value: "Latin Music", label: "Latin Music" },
  { value: "Melodies", label: "Melodies" },
  { value: "Opera", label: "Opera" },
  { value: "Orchestra", label: "Orchestra" },
  { value: "Pop", label: "Pop" },
  { value: "Progressive metal", label: "Progressive metal" },
  { value: "Punk rock", label: "Punk rock" },
  { value: "Qawalis", label: "Qawalis" },
  { value: "Rap", label: "Rap" },
  { value: "Reggae", label: "Reggae" },
  { value: "Remixes", label: "Remixes" },
  { value: "Rhythm & Blues", label: "Rhythm & Blues" },
  { value: "Rock", label: "Rock" },
  { value: "Sufi", label: "Sufi" },
  { value: "Techno", label: "Techno" },
  { value: "Trance music", label: "Trance music" },
  { value: "Western", label: "Western" },
];
export const sportsOptions = [
  { value: "Aerobics", label: "Aerobics" },
  { value: "American Football", label: "American Football" },
  { value: "Archery", label: "Archery" },
  { value: "Badminton", label: "Badminton" },
  { value: "Baseball", label: "Baseball" },
  { value: "Basketball", label: "Basketball" },
  { value: "Billiards / Snooker / Pool", label: "Billiards / Snooker / Pool" },
  { value: "Bowling", label: "Bowling" },
  { value: "Boxing", label: "Boxing" },
  { value: "Cricket", label: "Cricket" },
  { value: "Cycling", label: "Cycling" },
  { value: "Football", label: "Football" },
  { value: "Golf", label: "Golf" },
  { value: "Gym / Bodybuilding", label: "Gym / Bodybuilding" },
  { value: "Handball", label: "Handball" },
  { value: "Hockey", label: "Hockey" },
  { value: "Horseback Riding", label: "Horseback Riding" },
  {
    value: "Jogging / Walking / Running",
    label: "Jogging / Walking / Running",
  },
  { value: "Kabbadi", label: "Kabbadi" },
  { value: "Kho Kho", label: "Kho Kho" },
  { value: "Martial arts", label: "Martial arts" },
  { value: "Motor Racing", label: "Motor Racing" },
  { value: "Pilates", label: "Pilates" },
  { value: "Polo", label: "Polo" },
  { value: "Racquetball", label: "Racquetball" },
  { value: "Rugby", label: "Rugby" },
  { value: "Sailing / Boating / Rowing", label: "Sailing / Boating / Rowing" },
  { value: "Scuba Diving", label: "Scuba Diving" },
  { value: "Shooting", label: "Shooting" },
  {
    value: "Skating / Snowboarding / Skiing",
    label: "Skating / Snowboarding / Skiing",
  },
  { value: "Squash", label: "Squash" },
  { value: "Swimming / Water sports", label: "Swimming / Water sports" },
  { value: "Table tennis", label: "Table tennis" },
  { value: "Tennis", label: "Tennis" },
  { value: "Throwball", label: "Throwball" },
  { value: "Volleyball", label: "Volleyball" },
  { value: "Weight lifting", label: "Weight lifting" },
  { value: "Winter / Rink sports", label: "Winter / Rink sports" },
  {
    value: "Wrestling (Phelwani) / Khusti",
    label: "Wrestling (Phelwani) / Khusti",
  },
  { value: "Yoga / Meditatio", label: "Yoga / Meditatio" },
  { value: "Zumba", label: "Zumba" },
];
