export const heightToOptions = [
  { value: "4ft 6in", label: "4ft 6in" },
  { value: "4ft 7in", label: "4ft 7in" },
  { value: "4ft 8in", label: "4ft 8in" },
  { value: "4ft 9in", label: "4ft 9in" },
  { value: "4ft 10in", label: "4ft 10in" },
  { value: "4ft 11in", label: "4ft 11in" },
  { value: "5ft", label: "5ft" },
  { value: "5ft 1in", label: "5ft 1in" },
  { value: "5ft 2in", label: "5ft 2in" },
  { value: "5ft 3in", label: "5ft 3in" },
  { value: "5ft 4in", label: "5ft 4in" },
  { value: "5ft 5in", label: "5ft 5in" },
  { value: "5ft 6in", label: "5ft 6in" },
  { value: "5ft 7in", label: "5ft 7in" },
  { value: "5ft 8in", label: "5ft 8in" },
  { value: "5ft 9in", label: "5ft 9in" },
  { value: "5ft 10in", label: "5ft 10in" },
  { value: "5ft 11in", label: "5ft 11in" },
  { value: "6ft", label: "6ft" },
  { value: "6ft 1in", label: "6ft 1in" },
  { value: "6ft 2in", label: "6ft 2in" },
  { value: "6ft 3in", label: "6ft 3in" },
  { value: "6ft 4in", label: "6ft 4in" },
  { value: "6ft 5in", label: "6ft 5in" },
  { value: "6ft 6in", label: "6ft 6in" },
  { value: "6ft 7in", label: "6ft 7in" },
  { value: "6ft 8in", label: "6ft 8in" },
  { value: "6ft 9in", label: "6ft 9in" },
  { value: "6ft 10in", label: "6ft 10in" },
  { value: "6ft 11in", label: "6ft 11in" },
  { value: "7ft", label: "7ft" },
];
export const maritalStatusOptions = [
  { value: "Any", label: "Any" },
  { value: "Never Married", label: "Never Married" },
  { value: "Widowed", label: "Widowed" },
  { value: "Divorced", label: "Divorced" },
  { value: "Awaiting divorce", label: "Awaiting divorce" },
];
