export const anualIncomeOptions = [
  { value: "0 - 1 Lakh", label: "0 - 1 Lakh" },
  { value: "1 - 2 Lakhs", label: "1 - 2 Lakhs" },
  { value: "2 - 3 Lakhs", label: "2 - 3 Lakhs" },
  { value: "3 - 4 Lakhs", label: "3 - 4 Lakhs" },
  { value: "4 - 5 Lakhs", label: "4 - 5 Lakhs" },
  { value: "5 - 6 Lakhs", label: "5 - 6 Lakhs" },
  { value: "6 - 7 Lakhs", label: "6 - 7 Lakhs" },
  { value: "7 - 8 Lakhs", label: "7 - 8 Lakhs" },
  { value: "8 - 9 Lakhs", label: "8 - 9 Lakhs" },
  { value: "9 - 10 Lakhs", label: "9 - 10 Lakhs" },
  { value: "10 - 12 Lakhs", label: "10 - 12 Lakhs" },
  { value: "12 - 14 Lakhs", label: "12 - 14 Lakhs" },
  { value: "14 - 16 Lakhs", label: "14 - 16 Lakhs" },
  { value: "16 - 18 Lakhs", label: "16 - 18 Lakhs" },
  { value: "18 - 20 Lakhs", label: "18 - 20 Lakhs" },
  { value: "20 - 25 Lakhs", label: "20 - 25 Lakhs" },
  { value: "25 - 30 Lakhs", label: "25 - 30 Lakhs" },
  { value: "30 - 35 Lakhs", label: "30 - 35 Lakhs" },
  { value: "35 - 40 Lakhs", label: "35 - 40 Lakhs" },
  { value: "40 - 45 Lakhs", label: "40 - 45 Lakhs" },
  { value: "45 - 50 Lakhs", label: "45 - 50 Lakhs" },
  { value: "50 - 60 Lakhs", label: "50 - 60 Lakhs" },
  { value: "60 - 70 Lakhs", label: "60 - 70 Lakhs" },
  { value: "70 - 80 Lakhs", label: "70 - 80 Lakhs" },
  { value: "80 - 90 Lakhs", label: "80 - 90 Lakhs" },
  { value: "90 Lakhs - 1 Crore", label: "90 Lakhs - 1 Crore" },
  { value: "1 Crore & Above", label: "1 Crore & Above" },
];

export const famStatusOptions = [
  { value: "Middle Class", label: "Middle Class" },
  { value: "Upper Middle Class", label: "Upper Middle Class" },
  { value: "Rich", label: "Rich" },
  { value: "Affluent", label: "Affluent" },
];

export const physicalStatusOptions = [
  { value: "Normal", label: "Normal" },
  { value: "Physically Challenged", label: "Physically Challenged" },
];

export const employedInOptions = [
  { value: "Government/PSU", label: "Government/PSU" },
  { value: "Private   ", label: "Private   " },
  { value: "Business", label: "Business" },
  { value: "Defence", label: "Defence" },
  { value: "Self Employed", label: "Self Employed" },
  { value: "Not Working", label: "Not Working" },
];

export const eatingHabitsOptions = [
  { value: "Vegetarian", label: "Vegetarian" },
  { value: "Non Vegetarian", label: "Non Vegetarian" },
  { value: "Eggetarian", label: "Eggetarian" },
];

export const drinkingHabitsOptions = [
  { value: "Never drinks", label: "Never drinks" },
  { value: "Drinks socially", label: "Drinks socially" },
  { value: "Drinks regularly", label: "Drinks regularly" },
];
export const smokingHabitsOptions = [
  { value: "Never smokes", label: "Never smokes" },
  { value: "Smokes occasionally", label: "Smokes occasionally" },
  { value: "Smokes regularly", label: "Smokes regularly" },
];
export const starOptions = [
  { value: "Ashwini", label: "Ashwini" },
  { value: "Bharani", label: "Bharani" },
  { value: "Karthigai", label: "Karthigai" },
  { value: "Rohini", label: "Rohini" },
  { value: "Mirigasirisham", label: "Mirigasirisham" },
  { value: "Thiruvathirai", label: "Thiruvathirai" },
  { value: "Punarpoosam", label: "Punarpoosam" },
  { value: "Poosam", label: "Poosam" },
  { value: "Ayilyam", label: "Ayilyam" },
  { value: "Makam", label: "Makam" },
  { value: "Pooram", label: "Pooram" },
  { value: "Uthiram", label: "Uthiram" },
  { value: "Hastham", label: "Hastham" },
  { value: "Chithirai", label: "Chithirai" },
  { value: "Swathi", label: "Swathi" },
  { value: "Visakam", label: "Visakam" },
  { value: "Anusham", label: "Anusham" },
  { value: "Kettai", label: "Kettai" },
  { value: "Moolam", label: "Moolam" },
  { value: "Pooradam", label: "Pooradam" },
  { value: "Uthradam", label: "Uthradam" },
  { value: "Thiruvonam", label: "Thiruvonam" },
  { value: "Avittam", label: "Avittam" },
  { value: "Sadhayam", label: "Sadhayam" },
  { value: "Puratathi", label: "Puratathi" },
  { value: "Uthirattathi", label: "Uthirattathi" },
  { value: "Revathi", label: "Revathi" },
];

export const raasiPairOptions = [
  { value: "Mesham", label: "Mesham", starPair: "Ashwini" },
  { value: "Mesham", label: "Mesham", starPair: "Bharani" },
  { value: "Mesham", label: "Mesham", starPair: "Karthigai" },
  { value: "Rishabam", label: "Rishabam", starPair: "Karthigai" },
  { value: "Rishabam", label: "Rishabam", starPair: "Rohini" },
  { value: "Mithunam", label: "Mithunam", starPair: "Mirigasirisham" },
  { value: "Rishabam", label: "Rishabam", starPair: "Mirigasirisham" },
  { value: "Mithunam", label: "Mithunam", starPair: "Thiruvathirai" },
  { value: "Katagam", label: "Katagam", starPair: "Punarpoosam" },
  { value: "Mithunam", label: "Mithunam", starPair: "Punarpoosam" },
  { value: "Katagam", label: "Katagam", starPair: "Poosam" },
  { value: "Katagam", label: "Katagam", starPair: "Ayilyam" },
  { value: "Simham", label: "Simham", starPair: "Makam" },
  { value: "Simham", label: "Simham", starPair: "Pooram" },
  { value: "Kanni", label: "Kanni", starPair: "Uthiram" },
  { value: "Simham", label: "Simham", starPair: "Uthiram" },
  { value: "Kanni", label: "Kanni", starPair: "Hastham" },
  { value: "Kanni", label: "Kanni", starPair: "Chithirai" },
  { value: "Tula", label: "Tula", starPair: "Chithirai" },
  { value: "Tula", label: "Tula", starPair: "Swathi" },
  { value: "Tula", label: "Tula", starPair: "Visakam" },
  { value: "Vrichigam", label: "Vrichigam", starPair: "Visakam" },
  { value: "Vrichigam", label: "Vrichigam", starPair: "Anusham" },
  { value: "Vrichigam", label: "Vrichigam", starPair: "Kettai" },
  { value: "Dhanus", label: "Dhanus", starPair: "Moolam" },
  { value: "Dhanus", label: "Dhanus", starPair: "Pooradam" },
  { value: "Dhanus", label: "Dhanus", starPair: "Uthradam" },
  { value: "Makara", label: "Makara", starPair: "Uthradam" },
  { value: "Makara", label: "Makara", starPair: "Thiruvonam" },
  { value: "Kumbha", label: "Kumbha", starPair: "Avittam" },
  { value: "Makara", label: "Makara", starPair: "Avittam" },
  { value: "Kumbha", label: "Kumbha", starPair: "Sadhayam" },
  { value: "Kumbha", label: "Kumbha", starPair: "Puratathi" },
  { value: "Meena", label: "Meena", starPair: "Puratathi" },
  { value: "Meena", label: "Meena", starPair: "Uthirattathi" },
  { value: "Meena", label: "Meena", starPair: "Revathi" },
];

export const doshamOptions = [
  { value: "No", label: "No" },
  { value: "Yes", label: "Yes" },
  { value: "Don't Know", label: "Don't Know" },
];
